### ISSUE TITLE
about minio and k8s csi

### ISSUE THREAD

**Issue by fantastic2085** [minio/jbod-csi-driver#1]
1. Is this interface still being maintained?
2. Must it be JBOD?Is an x86 server ok?
3.Support ReadWriteMany?

**Comment by wlan0** [comment]
Hi @fantastic2085! 

1. This is being maintained yes. It is brand new and still under development.
2. This does support readwritemany, and yes an x86 server is what we support. This CSI driver is not meant for drives presented outside of the x86 server. (eg. SCSI block devices are not supported)
