### ISSUE TITLE
About minio combining with K8S

### ISSUE THREAD

**Issue by fantastic2085** [minio/jbod-csi-driver#3]
4 servers, each server 4 piece of hard disk, one piece of hard disk used to install the system, the remaining three hard disk do raid 0 or LVM, make 3 disk 1 piece of logical drives, the operating system is centos7, logical disk formatted into XFS, perform the mount, the mount point/data, through four minio k8s deployment, use hostpath make minio can use server logical disk full capacity

**Would like to consult, the above deployment, whether feasible?**

If the above deployment scenario is feasible, how can you deploy your app via JBOD-CSI driver to use minio clusters Such as creating buckets or writing data to buckets? like test-app.yaml?

**Comment by harshavardhana** [comment]
yes @fantastic2085
